# SITE SETUP
# Guide: https://docs.hugoblox.com/tutorial/
# Documentation: https://docs.hugoblox.com/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Appearance
appearance:
  mode: system
  color: blue

# SEO
marketing:
  seo:
    site_type: Person
    local_business_type: ''
    org_name: 'Jules Rousseau'
    description: 'personnal web page, Jules Rousseau, intern Inria, Irisa, Rennes, cryptography, cybersecurity, mathematics, github'
    twitter: 'GetResearchDev'
  analytics:
    google_analytics: ''
    baidu_tongji: ''
    plausible: ''
    fathom: ''
    pirsch: ''
  verification:
    google: 'R-p8kGP5D7NpmkthFlH3ftdWeAAFxBde4Hg5ATGJmfY'
    baidu: ''

# Site header
header:
  navbar:
    enable: true
    blox: "navbar"
    fixed_to_top: false
    show_search: true
    show_theme_chooser: true
    logo:
      text: "Jules ROUSSEAU"
# Site footer
footer:
  copyright:
    notice: '© {year} Jules Rousseau'
    license:
      enable: true
      allow_derivatives: false
      share_alike: true
      allow_commercial: false

# Localization
locale:
  date_format: 'Jan 2, 2006'
  time_format: '3:04 PM'

# Site features
features:
  math:
    enable: false
  privacy_pack:
    enable: false
